### ISSUE TITLE
Suggestion: Link back to index.

### ISSUE THREAD

**Issue by ConfusedVorlon** [harrison-broadbent/better_mailer_previews#10]
I really like the gem. Thank you.

Small suggestion - it would be great to have a link back to the index from an individual mailer page.

Perhaps a back arrow before the top title?

**Comment by harrison-broadbent** [comment]
great idea 👍 will do!

**Comment by harrison-broadbent** [comment]
Done! thank you for the suggestion @ConfusedVorlon !

**Comment by ConfusedVorlon** [comment]
Nice - Thank you :)
