### ISSUE TITLE
Question: Support for `params` with mailer#show

### ISSUE THREAD

**Issue by maxwell** [harrison-broadbent/better_mailer_previews#12]
Hi!

We have been enjoying `better_mailer_previews` at @backerkit, thank you for the gem.

We started using BMP for a bit of an "off label" use, and I was wondering if you would be interested in supporting a small revision to let us lean into it a bit more.

We have found that enabling BMP in production, behind a "staff" guard, has been a super useful tool for allowing non technical team members to stay up to date with the current copy of the various emails our app sends.

We recently implemented a feature that allows staff to write an email to get sent to users.  We started to pass a param to the mailer preview URL, which let us "select" which record to use to back the mailer preview.  This currently works if I link straight to the rails preview version of the URL, but it does seem like BMP is caching the calculated paths somehow which is preventing this from working in a production env.  

Would you be open to a PR that just passed along the params to the iframe, if they are present?

**Comment by harrison-broadbent** [comment]
Hey i'm stoked that you're using BMP and finding it useful!

I'm definitely open to a PR, if you're happy to put it together I can jump onto it and turn in around quickly. 
I get the feeling you want to be looking in `app/controllers/better_mailer_previews/mailers_controller.rb`, specifically in the show action where I'm constructing the URL path, and I can see I'm not passing through params. 

Can you expand on this a bit more for me? Just out of curiosity, I'm wondering what's going on here:
> We recently implemented a feature that allows staff to write an email to get sent to users. We started to pass a param to the mailer preview URL, which let us "select" which record to use to back the mailer preview. This currently works if I link straight to the rails preview version of the URL, but it does seem like BMP is caching the calculated paths somehow which is preventing this from working in a production env.

And how did you end up implementing a staff guard?

Thanks!

**Comment by harrison-broadbent** [comment]
I've just released `v1.0.3` of this gem which _should_ correctly pass through query params 👍
