### ISSUE TITLE
Hello 👋🏼  from Maily

### ISSUE THREAD

**Issue by markets** [harrison-broadbent/better_mailer_previews#14]
Hello @harrison-broadbent 👋🏼 

This is not an issue! Just wanted to say hello 👋🏼 as I'm the creator and maintainer of Maily (https://github.com/markets/maily) and maybe we can share ideas/feedback to improve both projects.

From this project, I like a couple of features that we don't have in Maily:
- An index page with all the previews
- The resize thing to easily display the email in different screen sizes

Good job!

**Comment by harrison-broadbent** [comment]
Hey @markets! Thanks for reaching out, to be honest, I had no idea about Maily!

It looks really cool though (and much more fully featured that BMP!) — what stuff are you working on now for Maily?

**Comment by markets** [comment]
In the last 2 years I only made maintenance, new Rails and Ruby support and small documentation tweaks. I'd say Maily is mostly done software, 1st release was around 9 years ago. 

But of course if any good idea arise, I'd be really happy to integrate it. I think I'd try to implement something to properly support visualization in other devices (like mobile), like this gem does 👌. 

And finally, would be nice to introduce some day something like this: https://github.com/markets/maily/issues/6, but to be honest, with [versions](https://github.com/markets/maily?tab=readme-ov-file#email-versions) you can already have different pre-defined versions for each email.
