### ISSUE TITLE
TailwindCSS fail to load on my setup

### ISSUE THREAD

**Issue by skatkov** [harrison-broadbent/better_mailer_previews#17]
I gave better_mailer_previews a try, but run into the following page:
<img width="1074" alt="Screenshot 2024-06-11 at 13 35 06" src="https://github.com/harrison-broadbent/better_mailer_previews/assets/544377/da6bda90-c10a-4b87-9175-8b895b385033">

It just failed to download tailwindcss.

These are the errors I'm seeing in console:

```
Loading failed for the <script> with source “https://cdn.tailwindcss.com/”. better_mailer_previews:9:47
Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at https://cdn.tailwindcss.com/ from being executed because it violates the following directive: “script-src 'self' https://assets.chddr.dev” better_mailer_previews
Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “style-src 'self' https://assets.chddr.dev” better_mailer_previews:10:1
```

**Comment by harrison-broadbent** [comment]
Hmm it looks like it might be related to a CSP you've set in your Rails app. 

If you've got a CSP in `config/initializers/content_security_policy.rb` you should add `https://cdn.tailwindcss.com/` to it. One other thing might be to disable any adblocker you've got enabled (but I don't think it's that).
