### ISSUE TITLE
Mail Preview with Namespace fails to load show action

### ISSUE THREAD

**Issue by dpaluy** [harrison-broadbent/better_mailer_previews#8]
My mailer preview is behind a namespace `Buyers::UserMailer` and `Vendors::UserMailer`
The preview works correctly, but the show action omits the namespace and it fails to load the email.

![CleanShot 2023-12-15 at 11 56 09@2x](https://github.com/harrison-broadbent/better_mailer_previews/assets/92692/ffe0aefa-33e1-476b-8c2b-fb44fd7ad84c)

**Comment by harrison-broadbent** [comment]
Thanks for reporting this @dpaluy ! Let me dig into this, I imagine i'm just not taking into account the namespace when i construct the URL.

**Comment by dpaluy** [comment]
I checked it briefly. One fix is required to the helper: https://github.com/harrison-broadbent/better_mailer_previews/blob/main/app/helpers/better_mailer_previews/application_helper.rb#L21
`url.split("/")[3...]`

But that's not enough, because a different routing is required. https://github.com/harrison-broadbent/better_mailer_previews/blob/main/config/routes.rb#L4

I created a quick patch: https://github.com/dpaluy/better_mailer_previews/commit/a8b6ba8cab265c9af21d2fb2f64cf5d15885b11e

Please let me know if you like it and I'll add specs

**Comment by harrison-broadbent** [comment]
oh shit thanks! I actually came up with the same changes 😅 

The other changes i need to make are in the `send_email` method to contantize the correct string. If you want to have a crack and specs or making any of those changes then go for it! I'll try to work on this myself too but I'll pull together both our contributions for the PR. If you do put up a PR, if possible could you do it against this repo and not a fork? then I can pull and commit to your PR and you'll appear as a contributor

**Comment by harrison-broadbent** [comment]
@dpaluy just merged a PR that should fix this! Let me know if there's anything you find, otherwise, thanks for opening the issue!
